# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 王帅的博客 #网站标题
subtitle: 慢慢积累 慢慢变强
description: 博客
author: wang
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://951759534.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false  #显示未来的文章
relative_link: false  #把链接改为与目录的相对地址
future: true    #显示未来的文章  
highlight:    #代码块的设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized      #默认分类
category_map:                 #分类别名
tag_map:                      #标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10        #每页显示的文章量   (0表示关闭分页功能)
pagination_dir: per_page        分页目录

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jacman
#search
algolia:
      applicationID: 'XM2EGJBDQ8'
      apiKey: '6351dc609b1a1aa51ab90ac38bc50557'
      adminApiKey: 'bfd1895dba6cd91bb0cef65cbd6551e8'
      indexName: 'index'
      chunkSize: 5000
      # Deployment
## Docs: https://hexo.io/docs/deployment.html
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
deploy:
  type: git
  repo:
      github: git@github.com:951759534/951759534.github.io.git,master
#      coding: git@git.coding.net:livecrystal/livecrystal.git,master